AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'myfirstsamproj

  Sample SAM Template for myfirstsamproj

  '
Globals:
  Function:
    Timeout: 3
Resources:
  GetEC2Regions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://demoakacs009/500b9876a508f8ba99f6928365a0a2ad
      Handler: main.lambda_handler
      Role: arn:aws:iam::794956478003:role/lambda
      Runtime: python3.6
      FunctionName: getEC2Regions
      Description: SAM demo
      Events:
        GetEC2regionAPI:
          Type: Api
          Properties:
            Path: /getec2region
            Method: get
Outputs:
  GetEC2regionAPI:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getec2region/
  GetEC2Regions:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetEC2Regions
      - Arn
